### ISSUE TITLE
Compléter readme.md

### ISSUE THREAD

**Issue by Frozzie89** [Frozzie89/Colimobis#34]
Décrire ces points dans le fichier README.MD :

- Description de l'application Colimobis
- dev : comment tester l'application sur web et sur mobile
- comment déployer et utiliser un container avec Docker

**Comment by Frozzie89** [comment]
@elwinner08 
J'ai complété le README.md (va voir sur le project directement en scroll en bas pour le lire : https://github.com/Frozzie89/Colimobis)

Si tu le souhaite, tu peux donner une description du projet (partie que j'ai laissée en TBD), sinon je peux le faire si tu préfère.
Idéallement en anglais au cas où ce projet est repris pas une autre personne... c'est toujours bon pour les best-practices.

**Comment by elwinner08** [comment]
Ok j'y réfléchirai

**Comment by Frozzie89** [comment]
README.md terminé
